#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           r_drive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           l_drive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           l_puncher,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           r_puncher,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           tread,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           l_cascade_top, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           r_cascade_bot, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           r_cascade_top, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          l_cascade_bot, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void puncher () {
	motor[l_puncher] = 127;
	motor[r_puncher] = 127;
	wait1Msec(5000);
}

void driveforward (int time){
	motor[l_drive] = 127;
	motor[r_drive] = 127;
	wait1Msec(time);
}
task main()
{
puncher ();
driveforward (5000);
}
